### ISSUE TITLE
Testing by docker containers?

### ISSUE THREAD

**Issue by le9i0nx** [nickjj/rolespec#31]
How do you like the idea to use a docker containers for testing.
Here is my example of it is raw but I think there is a sensible idea.
https://github.com/le9i0nx/ansible-syncthing/blob/master/.travis.yml

**Comment by nickjj** [comment]
Did it end up working for you? I haven't tried this pattern personally.

**Comment by le9i0nx** [comment]
Yes satisfactory.
Just my needs, also includes testing for different distributions, while only travis ubuntu.
And in this form it is more clean install.
Sometimes there are strange of event, but as long as I did not write it off on the elegance of the script.

**Comment by nickjj** [comment]
Nice, I'm sure someone will find it beneficial. You might even want to write a blog post about it.
